3 CONSTS $f300 RS_ADDR $f3fa PS_ADDR 0 HERESTART
RS_ADDR $a0 - CONSTANT SYSVARS
SYSVARS $80 + CONSTANT DRVMEM
DRVMEM CONSTANT KBD_MEM
DRVMEM 3 + CONSTANT GRID_MEM
DRVMEM 6 + CONSTANT FDMEM
DRVMEM 13 + CONSTANT UNDERCUR \ char under cursor
DRVMEM 14 + CONSTANT RXTX_MEM 
120 LOAD \ nC,
ARCHM Z80A XCOMPL Z80H TRS804PM
XCOMPH Z80C COREL Z80H ASMH TRS804PL
ALIAS FD@ (blk@)
ALIAS FD! (blk!)
BLKSUB GRIDSUB RXTXSUB TRS804PH
: INIT GRID$ KBD$ BLK$ FD$ $e CL$ ( 9600 bauds ) ;
XWRAP
