3 VALUES RS_ADDR $f300 PS_ADDR $f3fa HERESTART 0
RS_ADDR $90 - VALUE SYSVARS
SYSVARS $80 + VALUE DRVMEM
DRVMEM VALUE KBD_MEM
DRVMEM 3 + VALUE GRID_MEM
DRVMEM 6 + VALUE FDMEM
DRVMEM 9 + VALUE UNDERCUR \ char under cursor
120 LOAD \ nC,
ARCHM Z80A XCOMPL Z80H TRS804PM
XCOMPH Z80C COREL Z80H ASMH TRS804PL
X' FD@ ALIAS (blk@)
X' FD! ALIAS (blk!)
BLKSUB GRIDSUB TRS804PH
: INIT GRID$ KBD$ BLK$ FD$ ;
XWRAP
