( This is xcomp code that is common to both stage and forth
  binaries. )
0xff00 CONSTANT RS_ADDR
0xfffa CONSTANT PS_ADDR
RS_ADDR 0xb0 - CONSTANT SYSVARS
SYSVARS 0xa0 + CONSTANT GRID_MEM
0 CONSTANT HERESTART
2 LOAD
262 LOAD  ( xcomp low )
CREATE nativeidx 0 ,
: NATIVE CODE nativeidx @ DUP C, 1+ nativeidx ! ;
270 LOAD ( xcomp high )

HERE ORG !
0x15 ALLOT0
( END OF STABLE ABI )
HERE 4 + XCURRENT ! ( make next CODE have 0 prev field )
NATIVE EXIT
NATIVE (br)
NATIVE (?br)
NATIVE (loop)
NATIVE (b)
NATIVE (n)
NATIVE (s)
NATIVE >R
NATIVE R>
NATIVE 2>R
NATIVE 2R>
NATIVE EXECUTE
NATIVE ROT
NATIVE DUP
NATIVE ?DUP
NATIVE DROP
NATIVE SWAP
NATIVE OVER
NATIVE PICK
NATIVE 2DROP
NATIVE 2DUP
NATIVE 'S
NATIVE AND
NATIVE OR
NATIVE XOR
NATIVE NOT
NATIVE +
NATIVE -
NATIVE *
NATIVE /MOD
NATIVE !
NATIVE @
NATIVE C!
NATIVE C@
NATIVE PC!
NATIVE PC@
NATIVE I
NATIVE I'
NATIVE J
NATIVE BYE
NATIVE ABORT
NATIVE QUIT
NATIVE []=
NATIVE =
NATIVE <
NATIVE >
NATIVE FIND
NATIVE 1+
NATIVE 1-
NATIVE RSHIFT
NATIVE LSHIFT
NATIVE TICKS
NATIVE ROT>
NATIVE |L
NATIVE |M
353 LOAD ( forth low )
: (key?) 0 PC@ 1 ;
: EFS@
    1 3 PC! ( read )
    |M 3 PC! 3 PC! ( blkid )
    BLK( |M 3 PC! 3 PC! ( dest )
;
: EFS!
    2 3 PC! ( write )
    |M 3 PC! 3 PC! ( blkid )
    BLK( |M 3 PC! 3 PC! ( dest )
;
( fork between stage and forth begins here )
