2 VALUES RS_ADDR $ff00 PS_ADDR $fffa
RS_ADDR $80 - VALUE SYSVARS
8086A XCOMPL ARCHM
8086H HALC XCOMPH 8086C COREL 8086H HALC
CODE (blk@) POPf, 4 INT, DROPp, ;CODE
CODE (blk!) POPf, 5 INT, DROPp, ;CODE
BLKSUB
CODE (emit) POPp, 1 INT, ;CODE
CODE (key?) 2 INT, AH 0 MOVri, PUSHp, DUPp, ;CODE
2 VALUES COLS 80 LINES 25
CODE AT-XY ( x y ) POPf, 3 INT, DROPp, ;CODE
: INIT BLK$ ;
XWRAP
