2 CONSTS $ff00 RS_ADDR $fffa PS_ADDR
RS_ADDR $90 - VALUE SYSVARS
SYSVARS $409 - VALUE BLK_MEM
SYSVARS $80 + VALUE DRV_ADDR
DRV_ADDR 2 + VALUE GRID_MEM
ARCHM XCOMP 8086A XCOMPC 8086C COREL 
320 324 LOADR ( drivers )
ALIAS FD@ (blk@)
ALIAS FD! (blk!)
BLKSUB GRIDSUB
: INIT GRID$ BLK$ FD$ ;
XWRAP
