# See /doc/hw/z80/rc2014.txt for details
TARGET = os.bin
TARGETS = $(TARGET)
XCOMP ?= xcomp.fs
EMULEXEC = rc2014
EMUL_ARGS = -c$(BLKFS)
# for SIO, XCOMP=xcompsio.fs and EMUL_ARGS=-s
include ../common.mk
